<?php

return [
    'contact' => 'site/contact',
    'engineers' => 'engineers/index',
    'engineer/<id:\w+>' => 'engineers/details',
    'station/ships/<id:\w+>' => 'stations/ships',
    'station/ship-modules-<cat:\w+>/<id:\w+>' => 'stations/ship-modules',
    'station/ship-modules-hardpoint/<id:\w+>' => 'stations/ship-modules',
    'station/market/<id:\w+>' => 'stations/market',
    'station/<id:\w+>' => 'stations/details',
    'stations' => 'stations/index',
    'system-station/<sys_st:[\w\s\']+>' => 'stations/system-station',
    'system/get/<sys:[\w\s\']+>' => 'systems/system',
    'system/<id:\w+>' => 'systems/details',
    'systems' => 'systems/index',
    'shipyard-ships' => 'shipyard-ships/index',
    'ship-modules' => 'ship-modules/index',
    'commodities' => 'commodities/index',
    'trade-routes' => 'trade-routes/index',
    'materials' => 'materials/index',
    'material-traders' => 'material-traders/index',
    'rings' => 'rings/index',
    'user/login' => 'user/login',
    'user/logout' => 'user/logout',
    'user/signup' => 'user/signup',
    // admin dashboard
    'admin-dashboard/allegiance/view' => 'allegiance/view',
    'admin-dashboard/allegiance/update' => 'allegiance/update',
    'admin-dashboard/allegiance/delete' => 'allegiance/delete',
    'admin-dashboard/allegiance/create' => 'allegiance/create',
    'admin-dashboard/allegiance' => 'allegiance/index',
    // =========================================================================
    'admin-dashboard/modules-price-list/view' => 'modules-price-list/view',
    'admin-dashboard/modules-price-list/update' => 'modules-price-list/update',
    'admin-dashboard/modules-price-list/delete' => 'modules-price-list/delete',
    'admin-dashboard/modules-price-list/create' => 'modules-price-list/create',
    'admin-dashboard/modules-price-list' => 'modules-price-list/index',
    // =========================================================================
    'admin-dashboard/ships-price-list/view' => 'ships-price-list/view',
    'admin-dashboard/ships-price-list/update' => 'ships-price-list/update',
    'admin-dashboard/ships-price-list/delete' => 'ships-price-list/delete',
    'admin-dashboard/ships-price-list/create' => 'ships-price-list/create',
    'admin-dashboard/ships-price-list' => 'ships-price-list/index',
    // =========================================================================
    'admin-dashboard/ships-list/view' => 'ships-list/view',
    'admin-dashboard/ships-list/update' => 'ships-list/update',
    'admin-dashboard/ships-list/delete' => 'ships-list/delete',
    'admin-dashboard/ships-list/create' => 'ships-list/create',
    'admin-dashboard/ships-list' => 'ships-list/index',
    // =========================================================================
    'admin-dashboard/ship-modules-list/view' => 'ship-modules-list/view',
    'admin-dashboard/ship-modules-list/update' => 'ship-modules-list/update',
    'admin-dashboard/ship-modules-list/delete' => 'ship-modules-list/delete',
    'admin-dashboard/ship-modules-list/create' => 'ship-modules-list/create',
    'admin-dashboard/ship-modules-list' => 'ship-modules-list/index',
    // =========================================================================
    'admin-dashboard' => 'admin/index',
    '<action:(captcha)>'  => 'site/<action>',
    // '<controller>/<action>' =>  '<controller>/<action>',
    '' => 'site/index'
];
