import '../../../node_modules/bootstrap/js/dist/base-component.js';
// import '../../../node_modules/bootstrap/js/src/alert.js';
import '../../../node_modules/bootstrap/js/dist/button.js';
// import '../../../node_modules/bootstrap/js/src/carousel.js';
import '../../../node_modules/bootstrap/js/dist/collapse.js';
import '../../../node_modules/bootstrap/js/dist/dropdown.js';
// import '../../../node_modules/bootstrap/js/src/modal.js';
// import '../../../node_modules/bootstrap/js/src/offcanvas.js';
import '../../../node_modules/bootstrap/js/dist/popover.js';
// import '../../../node_modules/bootstrap/js/src/scrollspy.js';
// import '../../../node_modules/bootstrap/js/src/tab.js';
// import '../../../node_modules/bootstrap/js/src/toast.js';
import '../../../node_modules/bootstrap/js/dist/tooltip.js';